"""add follows.followee_id index

Revision ID: 79eaa3794e1d
Revises: 80080e70e043
Create Date: 2026-07-02 09:26:26.164616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79eaa3794e1d'
down_revision: Union[str, Sequence[str], None] = '80080e70e043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_follows_followee_id', 'follows', ['followee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_followee_id', table_name='follows')
    # ### end Alembic commands ###
